/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Body.glb --transform -o C:\Users\emanu\wing-configurator\public\Body.jsx --shadows 
Files: .\Body.glb [512.56KB] > C:\Users\emanu\wing-configurator\public\Body-transformed.glb [56.88KB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Body(props) {
  const { nodes, materials } = useGLTF("/models/Body-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["GEO-body_male_realistic"].geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Body-transformed.glb");
