/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Body.glb --transform -o C:\Users\emanu\wing-configurator\public\Body.jsx --shadows 
Files: Body.glb [1.15MB] > C:\Users\emanu\wing-configurator\public\Body-transformed.glb [103.22KB] (91%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Body(props) {
  const { nodes, materials } = useGLTF("/models/Body-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_doll.geometry}
        material={materials["Stal_—_satynowa.002"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Body-transformed.glb");
